version: 2
enable-beta-ecosystems: true # Julia ecosystem
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/test"
    schedule:
      interval: "daily"
    groups:
      all-julia-packages:
        patterns:
          - "*"
