name = "DiffEqBase"
uuid = "2b5f629d-d688-5b77-993f-72d75c75574e"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "v5.7.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
TreeViews = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
RecursiveFactorization = "f2c3362d-daeb-58d1-803e-2bc74f2840b4"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1"
RecipesBase = ">= 0.1.0"
RecursiveArrayTools = ">= 0.12.3"
IteratorInterfaceExtensions = ">= 0.1.0"
StaticArrays = ">= 0.8.3"
TableTraits = ">= 0.3.0"
MuladdMacro = ">= 0.2.1"
Parameters = ">= 0.10.0"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"

[targets]
test = ["Test", "Distributions", "MuladdMacro", "SafeTestsets"]
